const {rows,snapshots,extractedAt}=window.SCORECARD_DATA;
const fmt=n=>new Intl.NumberFormat().format(Math.round(n));
const pct=(a,b)=>b?100*a/b:0;
const dateLabel=s=>new Date(s+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'});
const dur=ms=>{if(ms==null)return 'N/A';if(ms<60000)return Math.round(ms/1000)+'s';if(ms<3600000)return Math.round(ms/60000)+'m';let total=Math.round(ms/60000),h=Math.floor(total/60),m=total%60;return `${h}h${String(m).padStart(2,'0')}m`};
const qaRows=[['2026-09-02',16,60.9],['2026-09-03',35,61.0],['2026-09-04',9,63.3],['2026-09-05',35,65.0],['2026-09-07',35,62.3],['2026-09-08',15,62.0],['2026-09-09',35,68.6],['2026-09-10',35,74.6],['2026-09-11',35,74.1],['2026-09-14',34,73.8],['2026-09-15',34,75.0],['2026-09-16',12,69.2],['2026-09-17',13,69.6],['2026-09-18',18,73.9],['2026-09-21',21,78.6]];
let shareChart,csatChart;
const from=document.querySelector('#from'),to=document.querySelector('#to');from.value='2026-09-10';to.value='2026-09-16';
function aggregate(selected){const sum=(c,m)=>selected.reduce((a,r)=>a+r[`${c}_${m}`],0), weighted=(c,m,count)=>{let n=sum(c,count);return n?selected.reduce((a,r)=>a+r[`${c}_${m}`]*r[`${c}_${count}`],0)/n:null};let x={};for(const c of ['ai','human','all'])x[c]={messages_sent:sum(c,'messages_sent'),closed_conversations_all:sum(c,'closed_conversations_all'),csat_score:weighted(c,'csat_score','csat_score_count')};return x}
function getData(a,b){let selected=rows.filter(r=>r.date>=a&&r.date<=b),exact=snapshots[`${a}|${b}`];return {selected,data:exact||aggregate(selected),exact:!!exact}}
function val(id,x){document.querySelector(id).textContent=x}
function update(){let a=from.value,b=to.value;if(!a||!b||a>b)return;let {selected,data,exact}=getData(a,b),days=Math.round((new Date(b)-new Date(a))/864e5)+1;val('#range',`${days} day${days===1?'':'s'} · ${dateLabel(a)} to ${dateLabel(b)}`);let qs=qaRows.filter(r=>r[0]>=a&&r[0]<=b),qn=qs.reduce((n,r)=>n+r[1],0),qavg=qn?qs.reduce((n,r)=>n+r[1]*r[2],0)/qn:null;val('#qaScore',qavg==null?'N/A':qavg.toFixed(1));val('#qaScoreSub',qavg==null?'no scored audits in selected range':`${qn} scored audits · weighted average`);val('#qaNote',qavg==null?'No numeric QA scores are logged in Form Responses 1 for the selected date range.':`Numeric QA scores from Form Responses 1 · ${dateLabel(qs[0][0])} to ${dateLabel(qs[qs.length-1][0])}.`);if(!selected.length){document.querySelector('#noData').hidden=false;document.querySelector('#dashboardData').hidden=true;return}document.querySelector('#noData').hidden=true;document.querySelector('#dashboardData').hidden=false;
const ai=data.ai,h=data.human,all=data.all;val('#aiMessages',fmt(ai.messages_sent));val('#replyShare',pct(ai.messages_sent,all.messages_sent).toFixed(1)+'%');val('#shareHeadline',pct(ai.messages_sent,all.messages_sent).toFixed(1)+'%');val('#shareSub',`${fmt(ai.messages_sent)} AI / ${fmt(h.messages_sent)} human / ${fmt(all.messages_sent)} total`);val('#aiCsat',ai.csat_score.toFixed(2));val('#humanCsat',h.csat_score.toFixed(2));val('#aiClosures',fmt(ai.closed_conversations_all));val('#closureShare',pct(ai.closed_conversations_all,all.closed_conversations_all).toFixed(1)+'%');val('#humanFrt',exact?dur(h.p50_first_response_time_outside_bh):'N/A');val('#p90Frt',exact?dur(all.p90_first_response_time_outside_bh):'N/A');val('#frtNote',exact?'Exact Richpanel percentile for this preset':'Percentiles are not combined from daily rows; choose Today, Yesterday, Last 7 Days, or Last 28 Days');
document.querySelector('#compare').innerHTML=`<tr><td>Messages sent</td><td>${fmt(ai.messages_sent)}</td><td>${fmt(h.messages_sent)}</td><td>${fmt(all.messages_sent)}</td></tr><tr><td>CSAT</td><td>${ai.csat_score.toFixed(2)}</td><td>${h.csat_score.toFixed(2)}</td><td>${all.csat_score.toFixed(2)}</td></tr><tr><td>Median first response</td><td>${exact?dur(ai.p50_first_response_time_outside_bh):'N/A'}</td><td>${exact?dur(h.p50_first_response_time_outside_bh):'N/A'}</td><td>${exact?dur(all.p50_first_response_time_outside_bh):'N/A'}</td></tr><tr><td>P90 first response</td><td>${exact?dur(ai.p90_first_response_time_outside_bh):'N/A'}</td><td>${exact?dur(h.p90_first_response_time_outside_bh):'N/A'}</td><td>${exact?dur(all.p90_first_response_time_outside_bh):'N/A'}</td></tr><tr><td>Median first resolution</td><td>${exact?dur(ai.p50_time_to_first_resolution_outside_bh):'N/A'}</td><td>${exact?dur(h.p50_time_to_first_resolution_outside_bh):'N/A'}</td><td>${exact?dur(all.p50_time_to_first_resolution_outside_bh):'N/A'}</td></tr><tr><td>Conversations closed</td><td>${fmt(ai.closed_conversations_all)}</td><td>${fmt(h.closed_conversations_all)}</td><td>${fmt(all.closed_conversations_all)}</td></tr>`;
const labels=selected.map(r=>new Date(r.date+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric'}));shareChart?.destroy();csatChart?.destroy();const opts={responsive:true,maintainAspectRatio:false,scales:{x:{grid:{display:false}},y:{grid:{color:'#edf1ef'}}}};shareChart=new Chart(document.querySelector('#shareChart'),{type:'line',data:{labels,datasets:[{label:'AI share',data:selected.map(r=>pct(r.ai_messages_sent,r.all_messages_sent)),borderColor:'#108474',backgroundColor:'#108474',tension:.25}]},options:opts});csatChart=new Chart(document.querySelector('#csatChart'),{type:'line',data:{labels,datasets:[{label:'AI',data:selected.map(r=>r.ai_csat_score),borderColor:'#108474'},{label:'Human only',data:selected.map(r=>r.human_csat_score),borderColor:'#8e59d1'}]},options:{...opts,scales:{x:{grid:{display:false}},y:{min:1,max:5}}}})}
from.onchange=to.onchange=update;document.querySelectorAll('[data-preset]').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('[data-preset]').forEach(x=>x.classList.remove('active'));btn.classList.add('active');let p=btn.dataset.preset,end=new Date('2026-09-22T12:00:00'),start=new Date(end);if(p==='custom'){from.focus();return}if(p==='yesterday'){end.setDate(end.getDate()-1);start=new Date(end)}else if(p!=='today')start.setDate(end.getDate()-Number(p)+1);from.value=start.toISOString().slice(0,10);to.value=end.toISOString().slice(0,10);update()});function shift(k){let a=new Date(from.value+'T12:00:00'),b=new Date(to.value+'T12:00:00'),d=Math.round((b-a)/864e5)+1;a.setDate(a.getDate()+k*d);b.setDate(b.getDate()+k*d);from.value=a.toISOString().slice(0,10);to.value=b.toISOString().slice(0,10);update()}document.querySelector('#prev').onclick=()=>shift(-1);document.querySelector('#next').onclick=()=>shift(1);val('#refreshTime',extractedAt);update();
